# CodeRabbit이 사용할 언어 설정 (한국어)
language: ko-KR

# AI 코치의 성격과 리뷰 스타일을 정의하는 지침
tone_instructions: >
  비판보다 개선 중심이며, 관련 문서 추천과 위트 있는 칭찬, P1~P5 우선순위 표시를 지킵니다.

# 코드 리뷰 설정
reviews:
  profile: chill # 리뷰 스타일: 편안하고 친근한 톤
  request_changes_workflow: false # Request Change 요청시 병합 비활성화 해제
  high_level_summary: true # PR 전체 요약 제공
  changed_files_summary: false # 개별 파일 요약은 비활성화 (중복 방지)
  sequence_diagrams: false # 시퀀스 다이어그램 생성 비활성화
  assess_linked_issues: true # 연결된 이슈 분석 활성화
  related_issues: false # 관련 이슈 추천 비활성화
  related_prs: false # 관련 PR 추천 비활성화
  suggested_labels: false # 라벨 추천 비활성화
  auto_apply_labels: false # 자동 라벨 적용 비활성화
  suggested_reviewers: false # 리뷰어 추천 비활성화
  auto_assign_reviewers: false # 자동 리뷰어 할당 비활성화
  poem: true # 리뷰 완료 후 시 작성 활성화 (재미 요소)

  # 특정 경로별 상세 리뷰 지침 설정
  path_instructions:
    - path: src/** # 백엔드 코드
      instructions: |
        - 1. 팀 컨벤션, 가독성, 예외처리, 테스트/확장/유지보수성, 모듈화, API/DB/보안 설계 기준을 기반으로 리뷰해주세요.
        - 2. 최신 트렌드, 불필요한 로직, 클린코드, 리팩터링, 서비스/도메인 설계, 공통 예외 처리, 확장성도 함께 확인해주세요.
        - 3. 각 피드백은 문제점, 대안, 장단점을 짧고 논리적으로 제시하고, 예시 코드가 있다면 간결히 포함해주세요.
        - 4. 팀 내 스타일 통일성도 확인해주세요.
        - 5. 리뷰를 남겨주는 부분은 해당 라인의 범위의 코멘트에 작성해주세요.
        - 6. 미작성한 테스트 코드 케이스가 있다면, 어떤 테스트가 필요한지 제안해주세요. (예: 컨트롤러는 E2E테스트, 나머지는 단위 테스트)
        - 7. 리뷰가 너무 많아서 피로감을 줄 수 있으니, 꼭 필요한 부분에 집중해주세요.
        - 8. 보안 상 치명적이거나, 추후 문제가 발생할 가능성이 높은 부분에 리뷰를 집중해주세요.

  # 자동 리뷰 기능 설정
  abort_on_close: true # PR이 닫히면 리뷰 중지
  disable_cache: false # 빠르고 효율적인 리뷰를 위해 캐시 기능 활성화
  auto_review:
    enabled: true # 자동 리뷰 활성화
    auto_incremental_review: false # 증분 리뷰 비활성화 (PR 이후 커밋/변경에 대해서는 리뷰하지 않도록 비활성화)
    base_branches: [".*"]

  # 코드 분석 도구(Tools)
  tools:
    hadolint: # Dockerfile 분석
      enabled: true
    gitleaks: # 민감정보 포함여부 확인
      enabled: true
    sqlfluff: # SQL 분석
      enabled: true

# 채팅 및 상호작용 설정
chat:
  auto_reply: true # 질문 시 자동 응답 활성화

# 지식 베이스 설정 (CodeRabbit이 참고할 문서들)
knowledge_base:
  opt_out: false # 지식베이스 사용 허용 (프로젝트의 리뷰들 확인)

  web_search:
    enabled: true # 웹 검색을 통한 최신 정보 활용

  learnings:
    scope: local # 학습 데이터를 현재 저장소로 제한

  issues:
    scope: local # 이슈 참조를 현재 저장소로 제한

  pull_requests:
    scope: local # PR 참조를 현재 저장소로 제한

# 코드 생성
code_generation:
  docstrings:
    language: ko-KR
    path_instructions:
      - path: src/**
        instructions: |
          - JavaDoc 공식 형식으로, 한글로 Docstring을 작성해주세요.
          - 메서드 목적, 파라미터, 반환값, 예외 정보를 명확하게 기술해 주세요.
          - 외부 API 등 공개 메서드는 상세히, 내부용은 핵심만 요약해 주세요.

  unit_tests:
    path_instructions:
      - path: src/**
        instructions: |
          - Controller는 인수테스트(API 엔드포인트 통합 테스트) 나머지 영역은 함수/클래스 단위의 단위 테스트
          - given-when-then 패턴을 적용
