export const ALARM_CATEGORY = {
  NEW_FRIEND_REQUEST: "NEW_FRIEND_REQUEST",
  NEW_FRIEND_PLACE_SHARING: "NEW_FRIEND_PLACE_SHARING",
  NEW_NOTICE: "NEW_NOTICE",
  NEW_KEYWORD_NOTICE: "NEW_KEYWORD_NOTICE",
  RENEW_TOP_RANK_PLACE: "RENEW_TOP_RANK_PLACE",
  RENEW_RANK_PLACE: "RENEW_RANK_PLACE",
} as const;

export interface AlarmContentType {
  category: string;
  name: string;
}
